name: Build and deploy .NET application to Container App ca-kazuki-dotnet
on:
  push:
    branches:
    - master
env:
  CONTAINER_APP_CONTAINER_NAME: webapp6
  CONTAINER_APP_NAME: ca-kazuki-dotnet
  CONTAINER_APP_RESOURCE_GROUP_NAME: rg-containerapps
  CONTAINER_REGISTRY_LOGIN_SERVER: crkazuki.azurecr.io
  DOCKER_FILE_PATH: WebApplication6/Dockerfile
  PROJECT_NAME_FOR_DOCKER: webapplication6
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.crkazuki_USERNAME_FFFF }}
        password: ${{ secrets.crkazuki_PASSWORD_FFFF }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.ca_kazuki_dotnet_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Installing containerapp extension"

          az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.1-py2.py3-none-any.whl --yes

          echo "Starting Deploying"

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} -i ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }} --registry-login-server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --registry-username  ${{ secrets.crkazuki_USERNAME_FFFF }} --registry-password ${{ secrets.crkazuki_PASSWORD_FFFF }} --debug
    - name: logout
      run: >
        az logout
